update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -22,14 +22,18 @@ jobs:
         run: npm ci
 
       # Check if the version has been incremented
-      # - name: Check if the version has been incremented
-      #   run: |
-      #     git fetch
-      #     VERSION_CHANGED=$(git diff origin/main -- package.json | grep '"version":')
-      #     if [ -z "$VERSION_CHANGED" ]; then
-      #       echo "Error: version in package.json has not been incremented."
-      #       exit 1
-      #     fi
+      - name: Check if the version has been incremented
+        run: |
+          git fetch
+          VERSION_CHANGED=$(git diff origin/main -- package.json | grep '"version":')
+          if [ -z "$VERSION_CHANGED" ]; then
+            echo "Error: version in package.json has not been incremented."
+            exit 1
+          fi
+
+      # Add this step to run your tests
+      - name: Run Tests
+        run: npm test
 
       # Build your project
       - name: Build
